### ISSUE TITLE
Issuing "make" command - problem

### ISSUE THREAD

**Issue by ghost** [gobolinux/Scripts#25]
On my slackware host system, I am trying to get the gobo-scripts ready (from today, as .zip download) just to test them out, before I may (hopefully) try them out on win10+ubuntu.

Anyway.

On my slackware system I have python 2.7.13 available locally at:

  **/Programs/Python/2.7.13**

When I run "make", I get this error:

for f in FindPackage GetAvailable GuessLatest CheckDependencies DescribeProgram UseFlags Corrections; \
do libf=lib/python2.7/site-packages/$f.py; \
   rm -f $libf; ln -nfs ../../../bin/$f $libf; \
done
cd lib/python2.7/site-packages && \
for f in *.py; \
do python -c "import `basename $f .py`"; \
done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "Alien.py", line 7, in <module>
    import CheckDependencies
  File "CheckDependencies.py", line 8, in <module>
    from FindPackage import *
  File "FindPackage.py", line 12, in <module>
    from GetAvailable import *
  File "GetAvailable.py", line 14, in <module>
    goboTemp = getGoboVariable('goboTemp')
  File "PythonUtils.py", line 109, in getGoboVariable
    os.environ[name] = value
  File "/Programs/Python/2.7.13/lib/python2.7/os.py", line 473, in __setitem__
    putenv(key, item)
TypeError: putenv() argument 2 must be string, not None
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "CheckDependencies.py", line 8, in <module>
    from FindPackage import *
  File "FindPackage.py", line 12, in <module>
    from GetAvailable import *
  File "GetAvailable.py", line 14, in <module>
    goboTemp = getGoboVariable('goboTemp')
  File "PythonUtils.py", line 109, in getGoboVariable
    os.environ[name] = value
  File "/Programs/Python/2.7.13/lib/python2.7/os.py", line 473, in __setitem__
    putenv(key, item)
TypeError: putenv() argument 2 must be string, not None
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "DescribeProgram.py", line 11, in <module>
    from GetAvailable import getGoboVariable
  File "GetAvailable.py", line 14, in <module>
    goboTemp = getGoboVariable('goboTemp')
  File "PythonUtils.py", line 109, in getGoboVariable
    os.environ[name] = value
  File "/Programs/Python/2.7.13/lib/python2.7/os.py", line 473, in __setitem__
    putenv(key, item)
TypeError: putenv() argument 2 must be string, not None
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "FindPackage.py", line 12, in <module>
    from GetAvailable import *
  File "GetAvailable.py", line 14, in <module>
    goboTemp = getGoboVariable('goboTemp')
  File "PythonUtils.py", line 109, in getGoboVariable
    os.environ[name] = value
  File "/Programs/Python/2.7.13/lib/python2.7/os.py", line 473, in __setitem__
    putenv(key, item)
TypeError: putenv() argument 2 must be string, not None
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "GetAvailable.py", line 14, in <module>
    goboTemp = getGoboVariable('goboTemp')
  File "PythonUtils.py", line 109, in getGoboVariable
    os.environ[name] = value
  File "/Programs/Python/2.7.13/lib/python2.7/os.py", line 473, in __setitem__
    putenv(key, item)
TypeError: putenv() argument 2 must be string, not None
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "UseFlags.py", line 7, in <module>
    goboSettings = getGoboVariable('goboSettings')
  File "PythonUtils.py", line 109, in getGoboVariable
    os.environ[name] = value
  File "/Programs/Python/2.7.13/lib/python2.7/os.py", line 473, in __setitem__
    putenv(key, item)
TypeError: putenv() argument 2 must be string, not None
make: *** [Makefile:21: python] Error 1

I am not sure where the problem is but perhaps it is because an environment
variable called goboTemp should be set. If so, to which value should I set
it? Could this be more easily documented please?

**Comment by shevegen** [comment]
Aha, I think I have found a link on the wiki:

https://github.com/gobolinux/Documentation/wiki/GoboPath

**Comment by hishamhm** [comment]
Did sourcing GoboPath into the environment fix the issue?

**Comment by hishamhm** [comment]
The Makefile certainly wasn't design to run over a bare system (the Rootless script used to prepare an environment to run it in).

**Comment by shevegen** [comment]
A moment - trying to find GoboPath and getting familiar with the layout ... :)

**Comment by Nuc1eoN** [comment]
The original issuer of this report is MIA, so closing :)
